name: "PR Checker"
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: assembleDebug
        uses: Raul6469/android-gradle-action@2.0.0
        with:
          script: assembleDebug
