name: "PR Checker"
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: vgaidarji/android-github-actions-build@v1.0.1
      with:
        args: "./gradlew assembleDebug"
